config/routes.rb
Rails.application.routes.draw do

  resources :event_images
  resources :guestlist_details

  resources :guestlists
  resources :simple_sites

  post "/events/event_id" => "events#event_id", :as => 'event_id'

  resources :user_businesses

  get 'address/new'

  get 'Impressum', to: 'simple_sites#impressum', as: 'impressum'
  get 'Datenschutzerklärung', to: 'simple_sites#privacy', as: 'privacy'
  get 'AGB', to: 'simple_sites#agb', as: 'agb'
  get '', to: 'welcomes#index', as: "welcomes"

  resources :events

  resources :branches

  devise_scope :user do
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'Branchen', to: 'branches#index'
  get 'Branche/:name', to: 'branches#show'
  get 'Branche/:name/bearbeiten', to:'branches#edit'
  get 'Branche/neu', to:'branches#new'
  patch 'Branche/:name',to: 'branches#update'

  post 'profiles/:id', to: 'profiles#destroy_photo'
  resources :profiles

  resources :services

  resources :businesses

   root to: 'welcomes#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :business
  belongs_to :branch
  has_many :event_hosts
  has_many :events, through: :event_hosts
  belongs_to :address
  belongs_to :contact

  validates :branch, :business_id, :name, presence: true
  validates :address, :contact, :name, presence: true



end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :set_businesses, only: [:new, :edit, :update, :create]
  before_action :set_user_services, only: [:index, :show, :edit, :update, :destroy]
  before_action :check_access_right, only: [:edit, :update, :destroy]
  before_action :check_for_events, only: [:destroy]

  respond_to :html

  def index
    @services = Service.all
    respond_with(@services)
  end

  def show
    respond_with(@service)
  end

  def new
    @service = Service.new
    @service.sameAddressLikeBusiness = true
    @service.sameContactLikeBusiness = true
    respond_with(@service)
  end

  def edit
  end

  def create

    @service = Service.create(service_params)

    if @service.sameContactLikeBusiness
      @service.contact_id = @service.business.contact_id
    elsif !@service.sameContactLikeBusiness
      contact = Contact.create(contact_params)
      @service.contact = contact
    end

    if @service.sameAddressLikeBusiness
      @service.address_id = @service.business.address_id
    elsif !@service.sameAddressLikeBusiness
      address = Address.create(address_params)
      @service.address = address
    end

    @service.save
    respond_with(@service)
  end

  def update
    @service.update(service_params)

    if @service.sameAddressLikeBusiness
      @service.address = @service.business.address
    else
      if @address.nil? || @service.address == @service.business.address
        if @address = Address.create(address_params)
          @service.address_id = @address.id
          @service.save
        end
      elsif !@service.address.update(address_params)
        @service.errors.add(:base, "Adresse nicht vollständig ausgefüllt")
      end
    end

    if @service.sameContactLikeBusiness
      @service.contact = @service.business.contact
    else
      if @contact.nil? || @service.contact == @service.business.contact
        if @contact = Contact.create(contact_params)
          @service.contact_id = @contact.id
          @service.save
        end
      elsif !@service.contact.update(contact_params)
        @service.errors.add(:base, "Kontakt nicht vollständig ausgefüllt")
      end
    end
    
    @service.save
    respond_with(@service)
  end

  def destroy
    @service.destroy
    respond_with(@service)
  end

  private
  def set_service
    #Check if Service exists:
    if Service.where(id: params[:id]).count <= 0
      flash[:alert] = "Dienstleistung wurde nicht gefunden"
      redirect_to services_path
      return
    end

    @service = Service.find(params[:id])
    @address = @service.address
    @contact = @service.contact
    @business = @service.business

    if current_user
      @profile = Profile.find_by_user_id(current_user.id)
    end
  end

  def set_businesses
    @businesses = User.find(current_user).businesses.all
  end

  def set_user_services

    if current_user
      @userBusinesses = User.find(current_user).businesses.all
      @userServices = Array.new

      @userBusinesses.each do |business|
        tmpServices = business.services.all

        tmpServices.each do |tmpService|
          @userServices.push(tmpService)
        end

      end

    end

  end

  def check_access_right
    if not @userServices.include?(@service)
      redirect_to root_path
    end
  end

  def service_params
    params.require(:service).permit(:description, :name, :teaser, :business_id, :branch_id, :sameAddressLikeBusiness, :sameContactLikeBusiness)
  end

  def address_params
    params.require(:address).permit(:city, :postalCode, :street1, :street2)
  end

  def contact_params
    params.require(:contact).permit(:phone, :mobilePhone, :mail)
  end

  def check_for_events
    if @service.event_services.count > 0
      flash[:alert] = "Bitte löschen Sie zuerst alle Events, in denen diese Dienstleistung Gastgeber ist"
      redirect_to service_path(@service)
    end
  end


end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>

    <div class="row">
      <% if @service.errors.any? %>
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 new-section">
            <div id="error_explanation">
              <h2>Es kann nicht gespeichert werden, weil:</h2>

              <ul>
                <% @service.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
      <% end %>
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 new-section">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 new-section">
            <h3 class="title">Angaben zur Dienstleistung</h3>

            <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
              </div>
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%= f.label :teaser %>
                <%= f.text_field :teaser, class: "form-control" %>
              </div>
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%= f.label :description %>
                <%= f.text_area :description, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 new-section">
            <h3 class="title">Unternehmen</h3>
            <% @businesses.each do |b| %>
                <%= f.radio_button :business_id, b.id %>
                <%= f.label "business_id_#{b.id}", b.name %><br>
            <% end %>
          </div>
        </div>
      </div>


      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 new-section">

        <h3 class="title">Kontakt</h3>

        <div class="row disablor">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <%= f.check_box :sameContactLikeBusiness %>
            <%= f.label :sameContactLikeBusiness %>
          </div>
        </div>
        <div class="row disableable">
          <%= fields_for :contact, @contact do |c| %>
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%= c.label :mail, 'E-Mail' %>
                <div class="input-group">
                  <span class="input-group-addon">@</span>
                  <%= c.text_field :mail, class: "form-control" %>
                </div>
              </div>
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%= c.label :phone, 'Telefonnummer' %>
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-phone fa-1x"></i></span>
                  <%= c.text_field :phone, class: "form-control" %>
                </div>
              </div>
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%= c.label :mobilePhone, 'Mobilfunknummer' %>
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-mobile-phone fa-2x"></i></span>
                  <%= c.text_field :mobilePhone, class: "form-control" %>
                </div>
              </div>
          <% end %>
        </div>
      </div>

      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 new-section">
        <h3 class="title">Adresse</h3>

        <div class="row disablor">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <%= f.check_box :sameAddressLikeBusiness %>
            <%= f.label :sameAddressLikeBusiness %>
          </div>
        </div>
        <div class="disableable">
          <%= render 'addresses/form' %>
        </div>
      </div>


      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 new-section">
        <h3 class="title">Branche</h3>

        <div class="accordionMod panel-group">
          <% BranchCategory.all.each do |sc| %>
              <div class="accordion-item">
                <h4 class="accordion-toggle"><%= sc.name %></h4>
                <section class="accordion-inner panel-body">
                  <% Branch.where(branchCategory_id: sc.id).each do |ssc| %>
                      <%= f.radio_button :branch_id, ssc.id %>
                      <%= f.label "branch_id_#{ssc.id}", ssc.name %><br>
                  <% end %>
                </section>
              </div>
          <% end %>
        </div>
      </div>

      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 new-section">
        <%= f.submit 'Speichern', {class: "btn btn-special btn-color"} %>
      </div>
    </div>
<% end %>

app/views/services/_index.html.erb
<table class="listingTable">
  <colgroup>
    <col width="130">
    <col width="190">
    <col width="420">
    <col width="150">
    <col width="120">
    <col width="150">
    <!--<col width="350">-->
  </colgroup>
  <thead>
  <tr>
    <th>Name</th>
    <th>Teaser</th>
    <th>Beschreibung</th>
    <th>eMail</th>
    <th>Telefon</th>
    <% if ! @isInBusiness %>
        <th>Unternehmen</th>
    <% end %>
    <th></th>
    <!--<th colspan="3"></th>-->
  </tr>
  </thead>

  <tbody>


  <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.teaser %></td>
        <td><%= service.description %></td>
        <td><a href="mailto:<%= service.contact.mail %>"><%= service.contact.mail %></a></td>
        <td><%= service.contact.phone %></td>
        <% if ! @isInBusiness %>
            <td><%= link_to service.business.name, business_path(service.business) %></td>
        <% end %>
        <td><%= link_to ' Anzeigen ', service %>


        <% if @userServices %>
            <% if ( @userServices.include?(service) )  %>
                <%= link_to 'Bearbeiten', edit_service_path(service) %>
            <% end %>
        <% end %>


        <% if @userServices %>
            <% if ( @userServices.include?(service) ) %>
                <%= link_to 'Löschen', service, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        <% end %>
        </td>
      </tr>

  <% end %>
  </tbody>
</table>

app/views/services/edit.html.erb
<% content_for :title, 'Dienstleistung bearbeiten' %>

<%= render 'form' %>

<%= link_to 'Zurück', @service %>

app/views/services/index.html.erb
<% content_for :title, 'Alle Dienstleistungen' %>

<%= link_to 'Suchen', branches_path, class:"col-md-2 btn btn-default btn-lg", style:'margin:5px;' %> <br /><br /><br />

<%= render 'index' %>

app/views/services/new.html.erb
<% content_for :title, 'Neue Dienstleistung' %>

<%= render 'form' %>
<br />
<% if current_user %>
    <% if User.find(current_user).profile %>
        <%= link_to 'Zurück zum Profil', profile_path(User.find(current_user).profile) %>
    <% end %>
<% end %>

<br />
<%= link_to 'Zurück', :back %>

app/views/services/show.html.erb
<% content_for :title, "#{@service.name}" %>
<table class="pretty-table">

  <tr>
    <td><strong>Teaser:</strong></td>
    <td><%= @service.teaser %></td>
  </tr>

  <tr>
    <td><strong>Beschreibung:</strong></td>
    <td><%= @service.description %></td>
  </tr>
  <tr>
    <td colspan="2">
      <h4>Kontakt</h4>
    </td>
  </tr>
  <tr>
    <td><strong>E-Mail:</strong></td>
    <td><a href="mailto:<%= @contact.mail %>"><%= @contact.mail %></a></td>
  </tr>

  <tr>
    <td><strong>Telefonnummer:</strong></td>
    <td><%= @contact.phone %></td>
  </tr>

  <tr>
    <td><strong>Mobilfunknummer:</strong></td>
    <td><%= @contact.mobilePhone %></td>
  </tr>

  <tr>
    <td colspan="2">
      <h4>Adresse</h4>
    </td>
  </tr>
  <tr>

    <td>Adresse:</td>
    <td>
      <%= @address.postalCode %>
      <%= @address.city %><br>
      <%= @address.street1 %><br>
      <%= @address.street2 %>
    </td>
  </tr>
</table>
<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 new-section">
    <table class="pretty-table">
      <tr>
        <td colspan="2">
          <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
              <h4>Events</h4>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 ">
              <% if (@userServices.include?(@service)) %>
                  <%= link_to '+', new_event_path, class: "btn btn-default btn-small pull-right" %>
              <% end %>
            </div>
          </div>
        </td>
      </tr>
      <% @business.events.each do |event| %>
          <tr>
            <td><strong><%= event.name %></strong></td>
            <td><%= link_to "Anzeigen", event, class: "pull-right" %></td>
          </tr>
      <% end %>
    </table>
  </div>
</div>
<br/>
<% if @userServices %>
    <% if (@userServices.include?(@service)) %>
        <%= link_to 'Dienstleistung bearbeiten', edit_service_path(@service) %>&nbsp;|&nbsp;
        <%= link_to 'Dienstleistung löschen', @service, method: :delete, data: {confirm: "Möchten Sie diese Dienstleistung wirklich entfernen?"} %>
        <br/>
    <% end %>
<% end %>

<%= link_to 'Zum Unternehmen: ' + @service.business.name, business_path(@service.business) %>
<br/>
<%= link_to 'Zurück', :back %>