config/routes.rb
Rails.application.routes.draw do

  resources :event_images
  resources :guestlist_details

  resources :guestlists
  resources :simple_sites

  post "/events/event_id" => "events#event_id", :as => 'event_id'

  resources :user_businesses

  get 'address/new'

  get 'Impressum', to: 'simple_sites#impressum', as: 'impressum'
  get 'Datenschutzerklärung', to: 'simple_sites#privacy', as: 'privacy'
  get 'AGB', to: 'simple_sites#agb', as: 'agb'
  get '', to: 'welcomes#index', as: "welcomes"

  resources :events

  resources :branches

  devise_scope :user do
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'Branchen', to: 'branches#index'
  get 'Branche/:name', to: 'branches#show'
  get 'Branche/:name/bearbeiten', to:'branches#edit'
  get 'Branche/neu', to:'branches#new'
  patch 'Branche/:name',to: 'branches#update'

  post 'profiles/:id', to: 'profiles#destroy_photo'
  resources :profiles

  resources :services

  resources :businesses

   root to: 'welcomes#index'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  before_action :set_user_businesses, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_access_right, only: [:show]
  before_action :check_access_right, only: [:edit, :update, :destroy]
  before_action :set_business_users, only: [:show]
  before_action :check_for_events, only: [:destroy]

  respond_to :html

  def index
    @businesses = Business.all
    respond_with(@businesses)
  end

  def show
    respond_with(@business)
  end

  def new

    @business = Business.new
    respond_with(@business)
  end

  def edit
  end

  def create
    @address = Address.create(address_params)
    @contact = Contact.create(contact_params)
    @business = Business.new(business_params)
    @business.address_id = @address.id
    @business.contact = @contact
    if(@business.save == false)
      @address.destroy
      @contact.destroy
      respond_with(@business)

    else
      current_user.add_role(:business_admin, @business)
      @business.user_businesses.create([{ user_id: current_user.id, position: :Administrator}])
      set_notice("erstellt")
      respond_with(@business)
    end

  end

  def update
    if @business.update(business_params)
      set_notice("bearbeitet")
    end
    @address.update(address_params)
    @contact.update(contact_params)
    respond_with(@business)
  end

  def destroy
    #First delete all services
    @services = @business.services.all
    if @services
      @services.each do |service|
        service.destroy
      end
    end

    #Then delete all user_businesses
    @user_businesses = @business.user_businesses.all
    if @user_businesses
      @user_businesses.each do |user_business|
        user_business.destroy
      end
    end

    @business.destroy
    set_notice("entfernt")

    current_user.remove_role(:business_admin, @business)

    respond_with(@business)
  end

  private
  def set_business
    #Check if business exists:
    if Business.where(id: params[:id]).count <= 0
      flash[:alert] = "Unternehmen wurde nicht gefunden"
      redirect_to businesses_path
      return
    end

    @business = Business.find(params[:id])
    @services = Service.where(business_id: @business.id)
    @address  = @business.address
    @contact  = @business.contact
  end


  def business_params
    params.require(:business).permit(:name)
  end

  def address_params
      params.require(:address).permit(:city, :postalCode, :street1, :street2)
  end

  def contact_params
    params.require(:contact).permit(:phone, :mobilePhone, :mail)
  end

  def set_user_businesses
    if current_user
      @userBusinesses = User.find(current_user).businesses.all
    end
  end

  def set_access_right
    if current_user
      if current_user.has_role? :business_admin, @business
        @admin = true
      else
        @admin = false
      end
    end
  end

  def check_access_right
    if current_user
      if not current_user.has_role? :business_admin, @business
        set_notice_no_access
        redirect_to businesses_path
      end
    else
      set_notice_no_access
      redirect_to businesses_path
    end
  end


  def set_business_users
    @businessUsers = @business.user_businesses.all
  end

  def set_notice(action)
    flash[:notice] = "'" + @business.name + "'" + " wurde " + action
  end

  def set_notice_no_access
    flash[:alert] = "Sie haben keine Berechtigung hierfür"
  end

  #check for existing events before removing the business
  def check_for_events
    if @business.event_businesses.count > 0
      flash[:alert] = "Bitte löschen Sie zuerst alle Events, in denen dieses Unternehmen Gastgeber ist"
      redirect_to business_path(@business)
    end
  end

end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
    <% if @business.errors.any? %>
        <div id="error_explanation">
          <h2>Es kann nicht gespeichert werden, weil:</h2>

          <ul>
            <% @business.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 new-section">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 new-section">
        <h3 class="title">Kontakt</h3>
        <%= fields_for :contact, @contact do |c| %>
            <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%= c.label :mail, 'E-Mail' %>
                <div class="input-group">
                  <span class="input-group-addon">@</span>
                  <%= c.text_field :mail, class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%= c.label :phone, 'Telefonnummer' %>
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-phone fa-1x"></i></span>
                  <%= c.text_field :phone, class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <%= c.label :mobilePhone, 'Mobilfunknummer' %>
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-mobile-phone fa-2x"></i></span>
                  <%= c.text_field :mobilePhone, class: "form-control" %>
                </div>
              </div>
            </div>
        <% end %>
      </div>

      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 new-section">
        <h3 class="title">Adresse</h3>
        <%= render 'addresses/form' %>
      </div>
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 new-section">
        <%= f.submit 'Speichern', {class: "btn btn-special btn-color"} %>
      </div>
    </div>
<% end %>

app/views/businesses/edit.html.erb
<% content_for :title, @business.name + ' bearbeiten' %>

<%= render 'form' %>

<%= link_to 'Zurück', @business %>

app/views/businesses/index.html.erb
<% content_for :title, 'Alle Unternehmen' %>

<table>
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.name %>&nbsp;</td>
        <td>&nbsp;|&nbsp;<%= link_to 'Übersicht', business %></td>

        <% if( @userBusinesses ) %>
            <% if( @userBusinesses.include?(business) ) and current_user.has_role? :business_admin, business %>
                <td>&nbsp;|&nbsp;<%= link_to 'Business-Informationen bearbeiten', edit_business_path(business) %></td>
            <% end %>
        <% end %>

        <% if( @userBusinesses ) %>
            <% if( @userBusinesses.include?(business) ) and current_user.has_role? :business_admin, business %>
        <td>&nbsp;|&nbsp;<%= link_to 'Löschen', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/businesses/new.html.erb
<% content_for :title, 'Neues Unternehmen' %>

<%= render 'form' %>

<%= link_to 'Zurück', businesses_path %>

app/views/businesses/show.html.erb
<% content_for :title, @business.name %>

<table class="pretty-table">
  <tr>
    <td colspan="2">
      <h4>Kontakt</h4>
    </td>
  </tr>
  <% unless @contact.mail.empty? %>
  <tr>
    <td><strong>E-Mail:</strong></td>
    <td><%= @contact.mail %></td>
  </tr>
    <% end %>
  <% unless @contact.phone.empty? %>
  <tr>
    <td><strong>Telefonnummer:</strong></td>
    <td><%= @contact.phone %></td>
  </tr>
  <% end %>
  <% unless @contact.mobilePhone.empty? %>
  <tr>
    <td><strong>Mobilfunknummer:</strong></td>
    <td><%= @contact.mobilePhone %></td>
  </tr>
  <% end %>

  <tr>
    <td colspan="2">
      <h4>Adresse</h4>
    </td>
  </tr>
  <tr>

    <td>Adresse:</td>
    <td>
      <%= @address.postalCode %>
      <%= @address.city %><br>
      <%= @address.street1 %><br>
      <%= @address.street2 %>
    </td>
  </tr>
</table>
<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 new-section">
    <table class="pretty-table">
      <tr>
        <td colspan="2">
          <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
              <h4>Events</h4>
            </div>

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 ">
              <% if @admin %>
                  <%= link_to '+', new_event_path, class: "btn btn-default btn-small pull-right" %>
              <% end %>
            </div>
          </div>
        </td>
      </tr>
      <% @business.events.each do |event| %>
          <tr>
            <td><strong><%= event.name %></strong></td>
            <td><%= link_to "Anzeigen", event, class: "pull-right" %></td>
          </tr>
      <% end %>

      <tr>
        <td colspan="2">
          <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
              <h4>Dienstleitungen</h4>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 ">
              <% if @admin %>
                  <%= link_to '+', new_service_path, class: "btn btn-default btn-small pull-right" %>
              <% end %>
            </div>
          </div>
        </td>
      </tr>

      <% servicessting = "" %>
      <% @business.services.each do |service| %>
          <% servicessting << "\n - " + service.name %>
          <tr>
            <td><strong><%= service.name %></strong></td>
            <td><%= link_to "Anzeigen", service_path(service), class: "pull-right" %></td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

<% if @businessUsers %>
    <p>
      <strong>Mitarbeiter:</strong>
    </p>
    <table class="listingTable">
      <tr>
        <th>Name</th>
        <th>Rang</th>
        <th></th>
      </tr>
      <% @businessUsers.each do |user_business| %>
          <tr>
            <td><%= user_business.user.email %></td>
            <td><%= user_business.position %></td>
            <td>
              <% usrProfile = user_business.user.profile %>
              <% if usrProfile %>
                  <%= link_to 'Profil zeigen', profile_path(user_business.user.profile) %>
              <% else %>
                  (kein Profil)
              <% end %>
              <% if @admin %>
                  &nbsp;|&nbsp;
                  <%= link_to 'Bearbeiten', edit_user_business_path(id: user_business.id, business: @business) %>
                  &nbsp;|&nbsp;
                  <%= link_to 'Aus Unternehmen entfernen', user_business, method: :delete, data: {confirm: "Möchten Sie wirklich den Mitarbeiter '#{user_business.user.email}' entfernen?"} %>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
<% else %>
    <p>Keine Mitarbeiter</p>
<% end %>

<p>
  <% if @admin %>
      <%= link_to 'Mitarbeiter hinzufügen', new_user_business_path(business: @business) %>
  <% end %>
</p>


<%= link_to 'Zurück', :back %>


<% if @admin %>
    | <%= link_to 'Unternehmen Bearbeiten', edit_business_path(@business) %> |


    <% if Service.where(business_id: @business.id).count > 0 %>
        <%= link_to 'Unternehmen löschen', @business, method: :delete, data: {confirm: "Möchten Sie wirklich Ihr Unternehmen '#{@business.name}' löschen?\nDamit löschen Sie auch folgende Dienstleistungen:\n#{servicessting}"} %>
    <% else %>
        <%= link_to 'Unternehmen löschen', @business, method: :delete, data: {confirm: "Möchten Sie wirklich Ihr Unternehmen '#{@business.name}' löschen?"} %>
    <% end %>
<% end %>