config/routes.rb
Rails.application.routes.draw do

  resources :event_images
  resources :guestlist_details

  resources :guestlists
  resources :simple_sites

  post "/events/event_id" => "events#event_id", :as => 'event_id'

  resources :user_businesses

  get 'address/new'

  get 'Impressum', to: 'simple_sites#impressum', as: 'impressum'
  get 'Datenschutzerklärung', to: 'simple_sites#privacy', as: 'privacy'
  get 'AGB', to: 'simple_sites#agb', as: 'agb'
  get '', to: 'welcomes#index', as: "welcomes"

  resources :events

  resources :branches

  devise_scope :user do
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'Branchen', to: 'branches#index'
  get 'Branche/:name', to: 'branches#show'
  get 'Branche/:name/bearbeiten', to:'branches#edit'
  get 'Branche/neu', to:'branches#new'
  patch 'Branche/:name',to: 'branches#update'

  post 'profiles/:id', to: 'profiles#destroy_photo'
  resources :profiles

  resources :services

  resources :businesses

   root to: 'welcomes#index'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  resourcify
  belongs_to :branchCategory
  has_many :services

  validates :name, uniqueness: true
  validates :name, :branchCategory, presence: true
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  load_and_authorize_resource
  before_action :set_branch_by_name, only: [:show, :edit, :update, :destroy]
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @branches = Branch.all
    respond_with(@branches)
  end

  def show
    respond_with(@branch)
  end

  def new
    @branch = Branch.new
    respond_with(@branch)
  end

  def edit
  end

  def create
    flash[:notice] = "Branche erfolgreich erstellt."
    @branch = Branch.new(branch_params)
    @branch.save
    #respond_with(@branch)
    respond_to do |format|
      format.html { redirect_to action: "index"}
    end
  end

  def update
    @branch.update(branch_params)
    respond_with(@branch)

    respond_to do |format|
      if @branch.update(branch_params)
        name = @branch.name
        if name.include? ' '
          name[' '] = '_'
        end

        format.html { redirect_to "#{branch_path}/#{name}", notice: 'Branche wurde erfolgreich aktualisiert.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @branch.destroy
    respond_with(@branch)
  end

  private
  def set_branch_by_name
    name = params[:name].gsub('_',' ')
    @branch = Branch.where(name: name).first

    #Check if Branch exists:
    unless @branch
      flash[:alert] = "Branche wurde nicht gefunden"
      redirect_to branches_path
    end
  end

  def set_branch
    @branch = Branch.find(params[:id])
  end

  def set_service
    @services = Service.where(branch_id: @branch)
  end


  def branch_params
    params.require(:branch).permit(:name, :branchCategory_id)
  end

  def address_params
    params.require(:address).permit(:city, :postalCode, :street1, :street2)
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true %>
  </div>
    <div class="field">
      <% BranchCategory.all.each do |bc| %>
          <%= f.radio_button :branchCategory_id, bc.id, :required => true %>
          <%= f.label "branchCategory_id_#{bc.id}", bc.name %><br>
      <% end %>
    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<% content_for :title, 'Branche bearbeiten' %>

<%= render 'form' %>

<%= link_to 'Anzeigen', @branch %> |
<%= link_to 'Zurück', :back %>

app/views/branches/index.html.erb
<% content_for :title, "Branchen" %>

<script src="/assets/portfolio.js"></script>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <div id="options">
    <ul id="filters" class="option-set clearfix" data-option-key="filter">
      <li><a href="#filter" data-option-value="*" class="selected">All</a></li>
      <% BranchCategory.all.each do |bc|
          %>
          <li><a href="#filter" data-option-value=".<%= bc.name.gsub(/[ &,]/, '') %>"><%= bc.name %></a></li>
      <% end %>
    </ul>
  </div>
</div>
<div class="clearfix"></div>
<div class="col-lg-12  col-md-12 col-sm-12 col-xs-12 portfolio-wrap">
  <div class="row">
    <div class="portfolio">
      <% @branches.each do |b| %>
          <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 <%= b.branchCategory.name.gsub(/[ &,]/, '') %> jquery item">
            <%= link_to "Branche/#{b.name}" do %>
                <div class="portfolio-item">
                  <div class="portfolio-item-title">
                    <p>
                      <%= b.name %>
                    </p>
                  </div>
                  <div class="clearfix"></div>
                </div>
            <% end %>
          </div>
      <% end %>
    </div>
 </div>
</div>

<% if can? :update, :branch %>
<%= link_to 'Neue Branche erstellen', new_branch_path %>
<% end %>

app/views/branches/new.html.erb
<% content_for :title, "Neue Branche" %>

<%= render 'form' %>

<%= link_to 'Zurück', branches_path %>

app/views/branches/show.html.erb
<% content_for :title, "Branche: #{@branch.name}" %>

<div class="well">
  <h4 class="title">Filter:</h4>

  <form action="" method="get">
    <div class="row">
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <label for="location">Standort</label><br>
        <input type="text" class="form-control" placeholder="Münster" name="usrloc" value="<%= if @loc_checked then @loc_checked.address end  %>"  onClick="this.select(); this.focus()">
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <div class="row">
          <label class="col-lg-6" for="range">Umkreis:</label>
          <div class="col-lg-6 text-right" >
            <output name="amount" style="display: inline" for="range"><%= @range %></output>
            <span> km</span>
          </div>
        </div>
        <input type="range" class="form-control"  name="range" step="10" min="0" max="200" value="<%= @range %>"  oninput="amount.value=range.value">
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <button class="btn-color btn-normal col-lg-3 col-md-4 col-sm-6 col-xs-12" style="border:none;" type="submit">Filtern</button>
      </div>
    </div>
  </form>
</div>

<div class="well">
  <h3 class="title">Anbieter:</h3>

  <% if Service.where(branch_id: @branch.id).count == 0 %>
      <span>Keine Ergebnisse vorhanden für: "<%= @branch.name %>"</span>
  <% else %>
      <% success = false %>
      <div class="row">
        <% unless (@usr_loc.nil?) %>
            <div class="col-lg-12">
              <span>Ergebnisse beim Standort <i><%= "#{@loc_checked.address}"%></i> im Umkreis von <i><%= "#{@range}" %></i> km:</span>
            </div>
        <% end %>
        <% @services.each do |s| %>
            <% loc_to = Address.where(id: Business.where(id: s.business_id).first.address_id).first %>
            <% if (@usr_loc.nil? || ((!(@loc_checked.nil?) && !(loc_to.nil?)) && (/^[\d]+(\.[\d]+){0,1}$/ === @loc_checked.distance_to(loc_to).round(2).to_s) && (/^[\d]+(\.[\d]+){0,1}$/ === @range.to_s) )) %>
                <% if @usr_loc.nil? || (@loc_checked.distance_to(loc_to).round(2).to_i <= @range.to_i) %>
                    <% success = true %>
                    <div class="col-lg-12" style="margin:5px">
                      <div class="portfolio-item">
                        <div>
                          <h4 class="text-left">
                            <%= link_to s.name, service_path(s), {:style=>'color:#2EAEF0; font-weight: normal;'} %> vom Unternehmen: <%= link_to s.business.name, business_path(s.business), {:style=>'color:#2EAEF0;font-weight: normal;'} %>
                          </h4>
                          <div class="col-lg-6 col-sm-12">
                            <table class="pretty-table">
                              <% unless (@usr_loc.nil?) %>
                                  <tr>
                                    <td>Entfernung:</td>
                                    <td><%= @loc_checked.distance_to(loc_to).round(2) %> km</td>
                                  </tr>
                              <% end %>
                              <tr>
                                <td>Kurzbeschreibung:</td>
                                <td><%= s.teaser %></td>
                              </tr>
                              <tr>
                                <td>Kommt aus:</td>
                                <td><%= Address.where(id: Business.where(id: s.business_id).first.address_id).first.city %></td>
                              </tr>
                            </table>
                          </div>
                          <div class="col-lg-6 col-sm-12">
                            <table class="pretty-table">
                              <tr>
                                <td>Beschreibung:</td>
                                <td><%= s.description %><br/></td>
                              </tr>
                            </table>
                          </div>
                        </div>
                        <div class="clearfix"></div>
                      </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>
        <% unless success %>
            <div class="col-lg-12"><br>
              <span><i class="fa fa-frown-o fa-2x"></i>  Leider keine Ergebnisse gefunden.</span>
              <br><br>
              <span>Tipp: <strong>Suchumkreis vergrößern</strong></span>
            </div>
        <% end %>
      </div>
  <% end %>

</div>
<%= link_to 'Zurück zu "Alle Branchen"', branches_path %>