config/routes.rb
Rails.application.routes.draw do

  resources :event_images
  resources :guestlist_details

  resources :guestlists
  resources :simple_sites

  post "/events/event_id" => "events#event_id", :as => 'event_id'

  resources :user_businesses

  get 'address/new'

  get 'Impressum', to: 'simple_sites#impressum', as: 'impressum'
  get 'Datenschutzerklärung', to: 'simple_sites#privacy', as: 'privacy'
  get 'AGB', to: 'simple_sites#agb', as: 'agb'
  get '', to: 'welcomes#index', as: "welcomes"

  resources :events

  resources :branches

  devise_scope :user do
    match '/users/sign_out' => 'devise/sessions#destroy', via: [:get, :delete]
  end

  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'Branchen', to: 'branches#index'
  get 'Branche/:name', to: 'branches#show'
  get 'Branche/:name/bearbeiten', to:'branches#edit'
  get 'Branche/neu', to:'branches#new'
  patch 'Branche/:name',to: 'branches#update'

  post 'profiles/:id', to: 'profiles#destroy_photo'
  resources :profiles

  resources :services

  resources :businesses

   root to: 'welcomes#index'

end

app/models/guestlist_detail.rb
class GuestlistDetail < ActiveRecord::Base
  belongs_to :event
  has_one :guestlist
end

app/controllers/guestlist_details_controller.rb
class GuestlistDetailsController < ApplicationController
  before_action :set_guestlist_detail, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @guestlist_details = GuestlistDetail.all
    respond_with(@guestlist_details)
  end

  def show
    respond_with(@guestlist_detail)
  end

  def new
    @guestlist_detail = GuestlistDetail.new
    respond_with(@guestlist_detail)
  end

  def edit
  end

  def create
    @guestlist_detail = GuestlistDetail.new(guestlist_detail_params)
    @guestlist_detail.save
    respond_with(@guestlist_detail)
  end

  def update

    new = GuestlistDetail.new(guestlist_detail_params)
    if new.size == @guestlist_detail.size &&
        new.offer == @guestlist_detail.offer &&
        new.end_date == @guestlist_detail.end_date &&
        new.end_time == @guestlist_detail.end_time

      @guestlist_detail.update(guestlist_detail_params)
    else
      event = Event.find(@guestlist_detail.event)
      @guestlist_detail = GuestlistDetail.new(guestlist_detail_params)
      @guestlist_detail.event = event
      @guestlist_detail.save
    end

    unless guestlist_detail_params[:active] == "true"
      @guestlist_detail.active = false
      @guestlist_detail.save
    end

    respond_with(@guestlist_detail.event)
  end

  def destroy
    @guestlist_detail.active = false
    @guestlist_detail.save
    respond_with(@guestlist_detail.event)
  end

  private
    def set_guestlist_detail
      @guestlist_detail = GuestlistDetail.find(params[:id])
    end

    def guestlist_detail_params
      params.require(:guestlist_detail).permit(:event_id, :active, :size, :offer, :end_date, :end_time)
    end
end

app/helpers/guestlist_details_helper.rb
module GuestlistDetailsHelper
end

app/views/guestlist_details/_form.html.erb
<%= form_for(@guestlist_detail) do |f| %>
    <% if @guestlist_detail.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@guestlist_detail.errors.count, "error") %> prohibited this guestlist_detail from being
            saved:</h2>

          <ul>
            <% @guestlist_detail.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <% unless @guestlist_detail.active.nil? %>
            <div style="widht:100%">
              <%= f.check_box :active, { checked: @guestlist_detail.active  } , true, false %>
              <%= f.label :active, 'Gästeliste aktiviert' %>
            </div>
        <% end %>
        <%= f.label :offer, 'Angebot' %><br>
        <%= f.text_area :offer, class: "form-control small-textarea" %>
        <%= f.label :size, "Angebot limitiert für X Gäste" %><br>
        <%= f.number_field :size, class: "form-control" %>
        <%= f.label :end_date, "Angebot Endet:" %><br>
        <div id="datepair" class="input-daterange input-group">
          <%= f.text_field :end_date, {class: "date form-control", style: 'width:50%'} %>
          <%= f.text_field :end_time, {class: "time form-control", style: 'width:50%'} %>
        </div>
        <%= f.submit "Speichern", class: "btn btn-normal btn-color submit" %>
      </div>
    </div>
<% end %>

app/views/guestlist_details/edit.html.erb
<% content_for :title, "Gästeliste bearbeiten von: #{Event.find(@guestlist_detail.event_id).name}" %>

<%= link_to 'Zurück zum Event', event_path(Event.find(@guestlist_detail.event_id)) %>
<div class="author-content">
  <h3>Wichtiger Hinweis</h3>
  <p>Du kannst das Angebot für die Gästeliste jederzeit ändern!<br>
    ABER! Die Konditionen bleiben für Gäste gespeichert, die einem Angebot bereits beigetreten sind!<br>
  <br>
  <u>Du kannst keine Gäste von der Liste entfernten!</u></p>
</div>
<div class="divider"></div>
<%= render 'form' %>
<div class="divider"></div>
<%= link_to 'Zurück zum Event', event_path(Event.find(@guestlist_detail.event_id)) %>

app/views/guestlist_details/index.html.erb
<h1>Listing guestlist_details</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Active</th>
      <th>Size</th>
      <th>Offer</th>
      <th>End date</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guestlist_details.each do |guestlist_detail| %>
      <tr>
        <td><%= guestlist_detail.event %></td>
        <td><%= guestlist_detail.active %></td>
        <td><%= guestlist_detail.size %></td>
        <td><%= guestlist_detail.offer %></td>
        <td><%= guestlist_detail.end_date %></td>
        <td><%= guestlist_detail.end_time %></td>
        <td><%= link_to 'Show', guestlist_detail %></td>
        <td><%= link_to 'Edit', edit_guestlist_detail_path(guestlist_detail) %></td>
        <td><%= link_to 'Destroy', guestlist_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guestlist detail', new_guestlist_detail_path %>

app/views/guestlist_details/new.html.erb
<h1>New guestlist_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', guestlist_details_path %>

app/views/guestlist_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @guestlist_detail.event %>
</p>

<p>
  <strong>Active:</strong>
  <%= @guestlist_detail.active %>
</p>

<p>
  <strong>Size:</strong>
  <%= @guestlist_detail.size %>
</p>

<p>
  <strong>Offer:</strong>
  <%= @guestlist_detail.offer %>
</p>

<p>
  <strong>End date:</strong>
  <%= @guestlist_detail.end_date %>
</p>

<p>
  <strong>End time:</strong>
  <%= @guestlist_detail.end_time %>
</p>

<%= link_to 'Edit', edit_guestlist_detail_path(@guestlist_detail) %> |
<%= link_to 'Back', guestlist_details_path %>